name: build & deploy

on:
  push:
    branches:
      - master

jobs:
  freeze-site:
    name: Create static site with Frozen-Flask
    runs-on: ubuntu-latest
    # built from the Dockerfile in this repo
    container: benswift/acmc:0.2.0

    defaults:
      run:
        working-directory: /app

    steps:
    - uses: actions/checkout@v2

    - name: freeze ‚ùÑ
      run: |-
          poetry version
          poetry show
          poetry check
          poetry env info
          poetry install
          poetry run make freeze

    - name: deploy üöÄ
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
