name: build & deploy

on:
  push:
    branches:
      - master

jobs:
  freeze-site:
    name: Create static site with Frozen-Flask
    runs-on: ubuntu-latest
    # built from the Dockerfile in this repo
    container: benswift/acmc:0.2.0

    defaults:
      run:
        working-directory: /app

    steps:
    - uses: actions/checkout@v2

    - name: install deps ğŸ”¨
      run: poetry install --no-dev

    - name: freeze â„
      run: poetry run make freeze

    - name: deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
